# $Id: Makefile.config 388 2005-04-28 21:04:09Z mwp $
#
# Edit this file to match your compilation environment.
#

#
# Compile time definitions:
#   use -DIS_LITTLE_ENDIAN when compiling for a little endian architecture
#
OPTIONS = -DIS_LITTLE_ENDIAN

#
# C compiler and flags.
# Any ANSI compliant C compiler will work.
#
CC = gcc
CFLAGS = $(OPTIONS) $(ARCH) -O3 -ansi
LDFLAGS =

#
# Miscellaneous utilities.
# Define these to suit your environment.
#
TAR = tar
RM = rm

#
# Leave these alone.
#
SHELL =	/bin/sh
VERSION = 1.0
