/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'gcst'
*/

/* 118 */
enum AL_FILE_TYPE
{
  AL_TYPE_ALTB = 0x42544C41, // AL Table
  AL_TYPE_ALOD = 0x444F4C41, // AL Object Definition
  AL_TYPE_ALRD = 0x44524C41, // AL Record Prop
  AL_TYPE_ALSD = 0x44534C41, // AL Shader
  AL_TYPE_ALIG = 0x47494C41, // AL Image
  AL_TYPE_ALTM = 0x4D544C41, // AL Tile Map
  AL_TYPE_ALSN = 0x4E534C41, // AL Sound
  AL_TYPE_ALAR = 0x52414C41, // AL Archive
  AL_TYPE_ALMS = 0x534D4C41, // AL Mesh Collision
  AL_TYPE_ALCT = 0x54434C41, // AL Container
  AL_TYPE_ALFT = 0x54464C41, // AL Font
  AL_TYPE_ALMT = 0x544D4C41, // AL Motion
  AL_TYPE_ALPT = 0x54504C41, // AL Pad Trace
  AL_TYPE_ALTX = 0x58544C41, // AL Texture
  AL_TYPE_ALLZ = 0x5A4C4C41, // AL Compress
};

