#define QUICKBMS_VER_ZERO   0
#define QUICKBMS_VER_MAJ    12
#define QUICKBMS_VER_MIN    0
#define QUICKBMS_VER_FIX    0
#define QUICKBMS_VER        QUICKBMS_VER_ZERO,QUICKBMS_VER_MAJ,QUICKBMS_VER_MIN,QUICKBMS_VER_FIX
#define QUICKBMS_VER_STR    ""#QUICKBMS_VER_ZERO#"."#QUICKBMS_VER_MAJ#"."#QUICKBMS_VER_MIN#"."#QUICKBMS_VER_FIX#""
